title: Johannes Giorgis
theme: PaperMod
# baseURL: "https://johannesgiorgis.com/"

params:
  # Necessary for post nav links to show up on /posts and /projects
  # https://github.com/adityatelange/hugo-PaperMod/issues/940
  mainSections:
    - posts
    - projects
    - teaching
  label:
    text: "Home"

  # profile-mode
  profileMode:
    # Needs to be explicitly set
    enabled: true
    title: Johannes Giorgis
    # I changed this to use HTML instead of Markdown in index_profile.html
    subtitle: "{CS Master's student, Researcher, Serial COMP TA} @ <a href=\"https://unc.edu\">UNC</a>. <a href=\"/about\"><ins>More about me</ins></a>"
    imageUrl: "/me.jpg"
    imageWidth: 150
    imageHeight: 150
    imageTitle: Picture of me
    buttons:
      - name: Posts
        url: post
      - name: Tags
        url: /tags
      - name: Archives
        url: /archives

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      Welcome to my blog
      Multi-line string with \n separating them
  

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20